list_des_lots:
    path:     /get-list-lots
    defaults: { _controller: WsRestBundle:AchatLot:postGetListLot }
    methods: POST # token, prix
insert_address_livraison:
    path:     /get-list-lots
    defaults: { _controller: WsRestBundle:AchatLot:postInsertAddressLivraison }
    methods: POST # nomcomplet, numero, pays, region, codepostal, ville, voie
