list_des_lots:
    path:     /get-list-lots
    defaults: { _controller: WsRestBundle:AchatLot:postGetListLot }
    methods: POST # token, prix
insert_address_livraison:
    path:     /insert-addresse-livraison
    defaults: { _controller: WsRestBundle:AchatLot:postInsertAddressLivraison }
    methods: POST # token, nomcomplet, numero, id_pays, id_region, codepostal, ville, voie
list_des_lots_category:
    path:     /get-list-lots-category
    defaults: { _controller: WsRestBundle:AchatLot:getListLotCategory }
    methods: POST #category_id
check_buy_lot:
    path:     /check-lot
    defaults: { _controller: WsRestBundle:AchatLot:checkBuyLot }
    methods: POST #lot_id,token
