ws_rest_achat_prono_get_status:
    path:     /get-status
    defaults: { _controller: WsRestBundle:AchatProno:postGetStatus }
    methods: POST # token,
ws_rest_achat_prono_insert:
    path:     /insert
    defaults: { _controller: WsRestBundle:AchatProno:insertStatusAchatProno }
    methods: POST # token,