ws_rest_championat_matchs:
    path:     /get-with-matchs
    defaults: { _controller: WsRestBundle:Championat:getChampionatWithMatch }
    methods: GET
ws_rest_list_championat_with_match_valide:
    path:     /get-championat-matchs
    defaults: { _controller: WsRestBundle:Championat:getChampionatWithNationalMatch }
    methods: GET
ws_rest_list_championat_by_country:
    path:     /get-championat-by-country
    defaults: { _controller: WsRestBundle:Championat:getListChampionatByCountry }
    methods: POST
ws_rest_list_championat_with_matchs:
    path:     /get-championat-with-maths
    defaults: { _controller: WsRestBundle:Championat:getListeChampionatWithMatch }
    methods: GET
ws_rest_list_match_by_championat:
    path:     /get-list-match-by-championat
    defaults: { _controller: WsRestBundle:Championat:getListeMatchsBySelectedChampionat }
    methods: POST
ws_rest_list_pays_with_championat_matchs:
    path:     /get-list-pays-with-championat-matchs
    defaults: { _controller: WsRestBundle:Championat:getListePaysWithChampionatWithMatchs }
    methods: GET

ws_rest_list_championat_by_pays:
    path:     /get-list-championat-by-pays
    defaults: { _controller: WsRestBundle:Championat:getListChampionatBySelectedPays }
    methods: POST

#ws_rest_list_pays_with_championat_with_match:
 #   path:     /get-list-pays-with-championat-with-matchs
  #  defaults: { _controller: WsRestBundle:Championat:findListPaysWithChampionatWithMatchs }
   # methods: GET