ws_rest_inscription:
    path:     /inscription
    defaults: { _controller: WsRestBundle:Inscription:postUtilisateur }
    methods: POST

ws_rest_get_profil:
    path:     /profil
    defaults: { _controller: WsRestBundle:Inscription:getProfilUtilisateur }
    methods: GET

ws_rest_post_profil:
    path:     /profil/update
    defaults: { _controller: WsRestBundle:Inscription:postProfilUtilisateur }
    methods: POST