ws_rest_inscription:
    path:     /inscription
    defaults: { _controller: WsRestBundle:Inscription:postUserFromAndroid }
    methods: POST

ws_rest_get_profil:
    path:     /profil
    defaults: { _controller: WsRestBundle:Inscription:getProfilUtilisateur }
    methods: POST #token

ws_rest_post_profil:
    path:     /profil/update
    defaults: { _controller: WsRestBundle:Inscription:postProfilUtilisateur }
    methods: POST