ws_rest_inscription:
    path:     /
    defaults: { _controller: WsRestBundle:Pronostic:getUtilisateurAchatPromo }
    methods: GET
    
ws_rest_getChampionnat:
    path:     /getChampionnat
    defaults: { _controller: WsRestBundle:Pronostic:getChampionnat }
    methods: POST