ws_rest_homepage:
    path:     /
    defaults: { _controller: WsRestBundle:Default:index }
    
ws_rest_subscription:
    path:     /inscription
    defaults: { _controller: WsRestBundle:Inscription:postUserFromAndroid }
    methods: POST
    
ws_rest_get_profil:
    path:     /profil
    defaults: { _controller: WsRestBundle:Inscription:getProfilUtilisateur }
    methods: GET
ws_rest_post_profil:
    path:     /profil/update
    defaults: { _controller: WsRestBundle:Inscription:postProfilUtilisateur }
    methods: POST
ws_rest_authentication_post:
    path:     /authentication
    defaults: { _controller: WsRestBundle:Authentication:authentication }
    methods: POST
ws_rest_forgotten_password:
    path:     /forgotten_password/{email}
    defaults: { _controller: WsRestBundle:Authentication:forgottenPassword }
    methods: GET
ws_rest_forgotten_password_post:
    path:     /forgotten_password
    defaults: { _controller: WsRestBundle:Authentication:forgottenPassword }
    methods: POST
ws_rest_appyone_data:
    path:     /data
    defaults: { _controller: WsRestBundle:AppyOne:getData }
    methods: POST
route_prefix_ws_rest_mention:
    resource: "@WsRestBundle/Resources/config/routing/mention.yml"
    prefix:   /
route_prefix_ws_rest_championnat:
    resource: "@WsRestBundle/Resources/config/routing/championat.yml"
    prefix:   /championat
route_prefix_ws_rest_championnats:
    resource: "@WsRestBundle/Resources/config/routing/championats.yml"
    prefix:   /championats
route_prefix_ws_rest_pronostic:
    resource: "@WsRestBundle/Resources/config/routing/pronostic.yml"
    prefix:   /pronostic
route_prefix_ws_rest_live_score:
    resource: "@WsRestBundle/Resources/config/routing/livescore.yml"
    prefix:   /live-score
route_prefix_ws_rest_sondage:
    resource: "@WsRestBundle/Resources/config/routing/sondage.yml"
    prefix:   /sondage
route_prefix_ws_rest_pari:
    resource: "@WsRestBundle/Resources/config/routing/pari.yml"
    prefix:   /pari
route_prefix_ws_rest_recapitulation:
    resource: "@WsRestBundle/Resources/config/routing/recapitulation.yml"
    prefix:   /recapitulation
route_prefix_ws_rest_classement:
    resource: "@WsRestBundle/Resources/config/routing/classement.yml"
    prefix:   /classements
route_prefix_ws_rest_achats:
    resource: "@WsRestBundle/Resources/config/routing/achats.yml"
    prefix:   /achats
route_prefix_ws_rest_achats_lots:
    resource: "@WsRestBundle/Resources/config/routing/achat_lot.yml"
    prefix:   /achats-lots
route_prefix_ws_rest_achats_prono:
    resource: "@WsRestBundle/Resources/config/routing/achat_prono.yml"
    prefix:   /achats-prono
route_prefix_ws_rest_credit:
    resource: "@WsRestBundle/Resources/config/routing/credit.yml"
    prefix:   /credit
route_prefix_ws_rest_publicite:
    resource: "@WsRestBundle/Resources/config/routing/publicite.yml"
    prefix:   /publicites
route_prefix_ws_rest_pays_region:
    resource: "@WsRestBundle/Resources/config/routing/pays_region.yml"
    prefix:   /pays-region
route_prefix_get_profil:
    resource: "@WsRestBundle/Resources/config/routing/inscription.yml"
    prefix:   /users