index_administrator:
    path:     /
    defaults: { _controller: BackAdminBundle:Administrator:index }

edit_administrator:
    path:     /edit/{id}
    defaults: { _controller: BackAdminBundle:Administrator:edit }

add_roles_administrator:
    path:     /roles/add
    defaults: { _controller: BackAdminBundle:Administrator:addRoles }

list_roles_administrator:
    path:     /roles/list/{idAdmin}
    defaults: { _controller: BackAdminBundle:Administrator:listRoles }

edit_roles_administrator_droit:
    path:     /roles/list/{idAdmin}/droit/{idDroitAdmin}
    defaults: { _controller: BackAdminBundle:Administrator:editDroitRolesAdmin }
edit_roles_admin_droit:
    path:     /roles/edit/{id}
    defaults: { _controller: BackAdminBundle:Administrator:editDroitAdmin }