index_admin_email:
    path:     /
    defaults: { _controller: BackAdminBundle:Email:index }
index_admin_parameter:
    path:     /parameters
    defaults: { _controller: BackAdminBundle:Email:parameters }
test_email:
    path:     /test/email
    defaults: { _controller: BackAdminBundle:Email:testEmail }