index_admin_match:
    path:     /
    defaults: { _controller: BackAdminBundle:Match:index }
add_loto_foot:
    path:     /lotofoot/add
    defaults: { _controller: BackAdminBundle:Match:addLotofoot }
list_loto_foot:
    path:     /lotofoot
    defaults: { _controller: BackAdminBundle:Match:listLotofoot }

edit_loto_foot:
    path:     /lotofoot/{idLotoFoot}/edit/{id}
    defaults: { _controller: BackAdminBundle:Match:editLotofoot }
remove_loto_foot:
    path:     /lotofoot/{idLotoFoot}/remove/{id}
    defaults: { _controller: BackAdminBundle:Match:removeLotoFoot }
add_match_loto_foot:
    path:     /lotofoot/{idLotoFoot}/add-match/{id}
    defaults: { _controller: BackAdminBundle:Match:addMatchInLotoFoot }