index_admin_utilisateur:
    path:     /
    defaults: { _controller: BackAdminBundle:Utilisateur:index }
update_admin_utilisateur:
    path:     /update/{id}
    defaults: { _controller: BackAdminBundle:Utilisateur:updateUtilisateur }

remove_admin_utilisateur:
    path:     /remove/{id}
    defaults: { _controller: BackAdminBundle:Utilisateur:deleteUtilisateur }
details_admin_utilisateur:
    path:     /details/{id}
    defaults: { _controller: BackAdminBundle:Utilisateur:details }

list_admin_droit:
    path:     /droits
    defaults: { _controller: BackAdminBundle:Utilisateur:listDroit }

export_csv_utilisateur:
    path:     /exportcsv
    defaults: { _controller: BackAdminBundle:Utilisateur:exportCsvUtilisateur }
    
mvtCredit_utilisateur:
    path:     /credit/{id}
    defaults: { _controller: BackAdminBundle:Utilisateur:credit }
    
add_mvtCredit_utilisateur:
    path:   /creditAdd/{id_utilisateur}
    defaults: { _controller: BackAdminBundle:Utilisateur:addMvtCredit }

update_mvtCredit_utilisateur:
    path:   /updateMvtCredit/{id_mvtCredit}
    defaults: { _controller: BackAdminBundle:Utilisateur:updateMvtCredit }
remove_mvtCredit_utilisateur:
    path:   /removeMvtCredit/{id_mvtCredit}
    defaults: { _controller: BackAdminBundle:Utilisateur:removeMvtCredit }