front_signup_homepage:
    path:     /
    defaults: { _controller: BackSignupBundle:Default:index }

register:
    path:     /register
    defaults: { _controller: BackSignupBundle:Register:register }
login:
    path:     /login
    defaults: { _controller: BackSignupBundle:Security:login }
login_check:
    path:     /login_check
logout:
    path:     /logout

