<?php

namespace Api\DBBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function testIfUserExist($username, $email)
    {

        $dql = "SELECT u FROM ApiDBBundle:Utilisateur u
                WHERE u.username = :username or u.email =:email";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameters(array('username' => $username, 'email' => $email));
        if ($query->getResult()) {
            return true;
        }
        return false;
    }
    public function findByEmailArray($email)
    {

        $dql = "SELECT u FROM ApiDBBundle:Utilisateur u
                WHERE u.email =:email";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameters(array('email' => $email));
        return $query->getArrayResult();
    }
}
