<?php

namespace Api\DBBundle\Repository;

/**
 * TemplateMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateMailRepository extends \Doctrine\ORM\EntityRepository
{
}
