<?php

namespace Api\DBBundle\Repository;

/**
 * ClassMoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassMoisRepository extends \Doctrine\ORM\EntityRepository
{
}
