fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
api_db_homepage:
    path:     /
    defaults: { _controller: ApiDBBundle:Default:index }

add_lot:
    path:     /add
    defaults: { _controller: ApiDBBundle:Lots:addLot }
