<?php

namespace Api\DBBundle\Repository;

/**
 * DroitAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DroitAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
