<?php

namespace Api\DBBundle\Repository;

/**
 * AddressLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressLivraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
