<?php

namespace Api\DBBundle\Repository;

/**
 * AdresseSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseSocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
