<?php

namespace Api\DBBundle\Repository;

/**
 * ClassAnneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassAnneeRepository extends \Doctrine\ORM\EntityRepository
{
}
