<?php

namespace Api\DBBundle\Repository;

/**
 * ClassEmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassEmRepository extends \Doctrine\ORM\EntityRepository
{
}
