<?php

namespace Api\DBBundle\Repository;

/**
 * ConcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcoursRepository extends \Doctrine\ORM\EntityRepository
{
}
