<?php

namespace Api\DBBundle\Repository;

/**
 * ConcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcoursRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllConcours($column = null, $order = null){
        $dql = "SELECT co from ApiDBBundle:Concours co ";
        $order = strtoupper($order);
        if($column && $order && is_string($column) && is_string($order) && ($order == 'ASC' or $order == 'DESC')){
            $dql .= " ORDER BY co.".$column. " ".$order;
        }
        if(!$column && !$order){
            $dql .= " ORDER BY co.dateDebut DESC";
        }
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->getResult();
    }
}
