<?php

namespace Api\DBBundle\Repository;

/**
 * ConnectedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectedRepository extends \Doctrine\ORM\EntityRepository
{
}
