<?php

namespace Api\DBBundle\Repository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserWithDevice(){
        $dql = "SELECT d from ApiDBBundle:Device d
                LEFT JOIN d.utilisateur u  group by d.token ";
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->getResult();
    }
}
