<?php

namespace Api\DBBundle\Repository;

/**
 * DroitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DroitRepository extends \Doctrine\ORM\EntityRepository
{
}
