<?php

namespace Api\DBBundle\Repository;

/**
 * EquipeSigleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeSigleRepository extends \Doctrine\ORM\EntityRepository
{
}
