<?php

namespace Api\DBBundle\Repository;

/**
 * FacebookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacebookRepository extends \Doctrine\ORM\EntityRepository
{
}
