<?php

namespace Api\DBBundle\Repository;

/**
 * LiveScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiveScoreRepository extends \Doctrine\ORM\EntityRepository
{
}
