<?php

namespace Api\DBBundle\Repository;

/**
 * LotCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
