<?php

namespace Api\DBBundle\Repository;

/**
 * LotoFootRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotoFootRepository extends \Doctrine\ORM\EntityRepository
{
}
