<?php

namespace Api\DBBundle\Repository;

/**
 * LotoFoot7Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotoFoot7Repository extends \Doctrine\ORM\EntityRepository
{
}
