<?php

namespace Api\DBBundle\Repository;

/**
 * LotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCategoryLot(){

        $dql = "SELECT l from ApiDBBundle:Lot l LEFT JOIN l.lotCategory lc GROUP BY lc.category";
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->getResult();
    }
    
    /**
     * get Lots by Category
     *
     * @return mixed
     */
    public function getLotsByCategory($categoryId)
    {
        $query = $this->createQueryBuilder('lot')
            ->select('lot')
            ->join('lot.lotCategory', 'lotCategory')
            ->andWhere('lotCategory.id = :categoryId')
            ->setParameter('categoryId', $categoryId)
            ->orderBy('lot.id', 'asc')
            ->getQuery();

        return $results = $query->getResult();
    }
}
