<?php

namespace Api\DBBundle\Repository;

/**
 * MatchsCorrespondanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchsCorrespondanceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCorrespondanceEquipeDomicile($equipeDomicile){
        $dql = "SELECT mc from ApiDBBundle:MatchsCorrespondance mc
                WHERE mc.equipeNetbetSport LIKE :equipeDomicile ";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('equipeDomicile', '%'.$equipeDomicile.'%');
        return $query->getResult();
    }
    public function findCorrespondanceEquipeVisiteur($equipeVisiteur){
        $dql = "SELECT mc from ApiDBBundle:MatchsCorrespondance mc
                WHERE mc.equipeNetbetSport LIKE :equipeVisiteur ";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('equipeVisiteur', '%'.$equipeVisiteur.'%');
        return $query->getResult();
    }
}
