<?php

namespace Api\DBBundle\Repository;

/**
 * MatchsEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchsEventRepository extends \Doctrine\ORM\EntityRepository
{
}
