<?php

namespace Api\DBBundle\Repository;

/**
 * matchIndividuelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class matchIndividuelRepository extends \Doctrine\ORM\EntityRepository
{
}
