<?php

namespace Api\DBBundle\Repository;

/**
 * MatchsFluxCoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchsFluxCoteRepository extends \Doctrine\ORM\EntityRepository
{
}
