<?php

namespace Api\DBBundle\Repository;

/**
 * MvtCreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MvtCreditRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastSolde($idUser){
        $dql = "SELECT mc, MAX(mc.id) from ApiDBBundle:MvtCredit mc LEFT JOIN mc.utilisateur u WHERE u.id = :idUser ";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('idUser', $idUser);
        return $query->getResult();
    }
    
    /**
     * Get last by user
     * 
     * @param Utilisateur $user
     * @return object|null
     */
    public function getLastByUser($user){
        $qb = $this->createQueryBuilder('mc')
                    ->select('mc')
                    ->join('mc.utilisateur', 'user')
                    ->andWhere('user.id = :userId')
                    ->setParameter('userId', $user->getId())
                    ->orderBy('mc.id', 'DESC')
                    ->setMaxResults(1);            
        $query = $qb->getQuery();

        return $results = $query->getOneOrNullResult();
    }
}
