<?php

namespace Api\DBBundle\Repository;

/**
 * MvtCreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MvtCreditRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastSolde($idUser){
        $dql = "SELECT mc, MAX(mc.id) from ApiDBBundle:MvtCredit mc LEFT JOIN mc.utilisateur u WHERE u.id = :idUser ";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('idUser', $idUser);
        return $query->getResult();
    }
}
