<?php

namespace Api\DBBundle\Repository;

/**
 * MvtCreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MvtCreditRepository extends \Doctrine\ORM\EntityRepository
{
}
