<?php

namespace Api\DBBundle\Repository;

/**
 * MvtLotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MvtLotRepository extends \Doctrine\ORM\EntityRepository
{
}
