<?php

namespace Api\DBBundle\Repository;

/**
 * NotificationRecapitulationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRecapitulationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNoSended(){
        $dql ="SELECT nr from ApiDBBundle:NotificationRecapitulation nr
               LEFT JOIN nr.matchs m
               LEFT JOIN nr.utilisateur u
               WHERE nr.isNotificationSended = false ";
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->getResult();
    }
}
