<?php

namespace Api\DBBundle\Repository;

/**
 * OeufsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OeufsRepository extends \Doctrine\ORM\EntityRepository
{
}
