<?php

namespace Api\DBBundle\Repository;

/**
 * OeufsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OeufsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOeufs(){
        $dql = "SELECT o from ApiDBBundle:Oeufs o order by o.tarifOeufs";
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->getResult();
    }
}
