<?php

namespace Api\DBBundle\Repository;

/**
 * PaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * find all order by name
     * 
     * @return mixed
     */
    public function findAllOrdered()
    {
        $query = $this->createQueryBuilder('pays')
                ->select('pays')
                ->orderBy('pays.nomPays', 'asc')
                ->getQuery();

        return $query->getResult();
    }
}
