<?php

namespace Api\DBBundle\Repository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * find all order by name
     * 
     * @return mixed
     */
    public function findAllOrdered()
    {
        $query = $this->createQueryBuilder('region')
                ->select('region','pays')
                ->join('region.pays','pays')
                ->orderBy('region.nom', 'asc')
                ->getQuery();

        return $query->getResult();
    }
}
