<?php

namespace Api\DBBundle\Repository;

/**
 * TeamsCoresspondanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamsCoresspondanceRepository extends \Doctrine\ORM\EntityRepository
{
}
