<?php

namespace Api\DBBundle\Repository;

/**
 * TeamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTeamsByFluxCote($name){
        $dql = "SELECT t from ApiDBBundle:Teams t WHERE t.nomClub LIKE :nameteams or t.fullNameClub LIKE :nameteams";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('nameteams', '%'.$name.'%');
        return $query->getResult();
    }
}
