<?php

namespace Api\DBBundle\Repository;

/**
 * TeamsPaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamsPaysRepository extends \Doctrine\ORM\EntityRepository
{
}
