<?php

namespace Api\DBBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function testIfUserExist($username, $email)
    {

        $dql = "SELECT u FROM ApiDBBundle:Utilisateur u
                WHERE u.username = :username or u.email LIKE :email";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameters(array('username' => $username, 'email' => '%'.$email.'%'));
        if ($query->getResult()) {
            return true;
        }
        return false;
    }

    public function testIfEmailExist($email)
    {
        $dql = "SELECT u FROM ApiDBBundle:Utilisateur u
                WHERE  u.email =:email";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('email', $email);
        if ($query->getResult()) {
            return true;
        }
        return false;
        
    }
    public function findByEmailArray($email)
    {

        $dql = "SELECT u FROM ApiDBBundle:Utilisateur u
                WHERE u.email =:email";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameters(array('email' => $email));
        $res = $query->getArrayResult();
        if($res){
          return $res[0];  
        }
        return null;
        
    }

    public function getAllUtilisateurs($champ, $tri, $criteria = array()){

        $request = "";
        $addAnd = false;
        if(isset($criteria['criteria_username'])){
            $filter = $criteria['criteria_username'];
            $request = $request." WHERE u.username LIKE '%$filter%'" ;
            $addAnd = true;
        }
        if(isset($criteria['criteria_email'])){
            if($addAnd){
                $request = $request." AND ";
            }
            else{
                $request = $request." WHERE ";
            }
            $filter = $criteria['criteria_email'];
            $request = $request." u.email LIKE '%$filter%' " ;
        }
        if(isset($criteria['criteria_score_total'])){
            if($addAnd){
                $request = $request." AND";
            }
            $filter = $criteria['criteria_score_total'];
            $request = $request." AND WHERE u.mvtPoints = '$filter' " ;
        }

     
        
        if($tri and $champ){
            $dql = "SELECT u from ApiDBBundle:Utilisateur u" .
                    $request.
                    " ORDER by u.email ASC ";
            $query = $this->getEntityManager()->createQuery($dql);
            //$query->setParameters( array('tri' => $tri, 'champ' => $champ) );
            return $query->getResult();
        }
        $dql = "SELECT u from ApiDBBundle:Utilisateur u"
                . " $request";
        
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->getResult();
    }
}
