<?php

namespace Api\DBBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function testIfUserExist($username, $email)
    {

        $dql = "SELECT u FROM ApiDBBundle:Utilisateur u
                WHERE u.username = :username or u.email =:email";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameters(array('username' => $username, 'email' => $email));
        if ($query->getResult()) {
            return true;
        }
        return false;
    }

    public function testIfEmailExist($email)
    {
        $dql = "SELECT u FROM ApiDBBundle:Utilisateur u
                WHERE  u.email =:email";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('email', $email);
        if ($query->getResult()) {
            return true;
        }
        return false;
        
    }
    public function findByEmailArray($email)
    {

        $dql = "SELECT u FROM ApiDBBundle:Utilisateur u
                WHERE u.email =:email";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameters(array('email' => $email));
        $res = $query->getArrayResult();
        if($res){
          return $res[0];  
        }
        return null;
        
    }

    public function getAllUtilisateurs($champ, $tri){

        if($tri and $champ){
            $dql = "SELECT u from ApiDBBundle:Utilisateur u
                ORDER by u.email ASC ";
            $query = $this->getEntityManager()->createQuery($dql);
            //$query->setParameters( array('tri' => $tri, 'champ' => $champ) );
            return $query->getResult();
        }
        $dql = "SELECT u from ApiDBBundle:Utilisateur u";
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->getResult();
    }
}
