<?php

namespace Api\DBBundle\Repository;

/**
 * ParameterMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterMailRepository extends \Doctrine\ORM\EntityRepository
{
}
