<?php

namespace Api\DBBundle\Repository;

/**
 * MvtPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MvtPointRepository extends \Doctrine\ORM\EntityRepository
{
}
