<?php

namespace Api\DBBundle\Repository;

/**
 * LotoFoot15Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotoFoot15Repository extends \Doctrine\ORM\EntityRepository
{
}
