index_admin:
    path:     /
    defaults: { _controller: BackAdminBundle:Admin:index }

route_prefix_utilisateur:
    resource: "@BackAdminBundle/Resources/config/routing/utilisateur.yml"
    prefix:   /utilisateurs
route_prefix_administrateurs:
    resource: "@BackAdminBundle/Resources/config/routing/administrator.yml"
    prefix:   /administrateurs

route_prefix_admin_email:
    resource: "@BackAdminBundle/Resources/config/routing/email.yml"
    prefix:   /emails

