index_admin:
    path:     /
    defaults: { _controller: BackAdminBundle:Admin:index }

route_prefix_utilisateur:
    resource: "@BackAdminBundle/Resources/config/routing/utilisateur.yml"
    prefix:   /utilisateurs
route_prefix_administrateurs:
    resource: "@BackAdminBundle/Resources/config/routing/administrator.yml"
    prefix:   /administrateurs

route_prefix_admin_email:
    resource: "@BackAdminBundle/Resources/config/routing/email.yml"
    prefix:   /emails
route_prefix_admin_pronostic_promo:
    resource: "@BackAdminBundle/Resources/config/routing/pronostic.yml"
    prefix:   /pronostics
route_prefix_admin_match:
    resource: "@BackAdminBundle/Resources/config/routing/match.yml"
    prefix:   /matchs
route_prefix_admin_mention:
    resource: "@BackAdminBundle/Resources/config/routing/mentions.yml"
    prefix:   /mentions
route_prefix_admin_notification:
    resource: "@BackAdminBundle/Resources/config/routing/notification.yml"
    prefix:   /notification
route_prefix_admin_concours:
    resource: "@BackAdminBundle/Resources/config/routing/concours.yml"
    prefix:   /concours
route_prefix_admin_teams:
    resource: "@BackAdminBundle/Resources/config/routing/teams.yml"
    prefix:   /teams
route_prefix_admin_championat:
    resource: "@BackAdminBundle/Resources/config/routing/championat.yml"
    prefix:   /championnats
route_prefix_admin_lots:
    resource: "@BackAdminBundle/Resources/config/routing/lots.yml"
    prefix:   /lots
route_prefix_admin_achats:
    resource: "@BackAdminBundle/Resources/config/routing/achat.yml"
    prefix:   /achats
route_prefix_admin_publicite:
    resource: "@BackAdminBundle/Resources/config/routing/publicite.yml"
    prefix:   /publicites
route_prefix_admin_pays:
    resource: "@BackAdminBundle/Resources/config/routing/pays.yml"
    prefix:   /pays
route_prefix_admin_region:
    resource: "@BackAdminBundle/Resources/config/routing/region.yml"
    prefix:   /regions

route_prefix_admin_classement:
    resource: "@BackAdminBundle/Resources/config/routing/classement.yml"
    prefix:   /classements