<?php

namespace Api\DBBundle\Repository;

/**
 * DroitAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DroitAdminRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDroitByAdminId($idAdmin)
    {

        $dql = "SELECT da from ApiDBBundle:DroitAdmin as da WHERE da.admin = :idAdmin ";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('idAdmin', $idAdmin);
        $query->getResult();

    }
}
