services:
#    back_authentication.example:
#        class: Back\AuthenticationBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    app.form.registration:
        class: Back\AuthenticationBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }