<?php

namespace Api\DBBundle\Repository;

/**
 * VoteUtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteUtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
